# Site settings
title: Steve Hartzog
tagline: '' 
email: shartzog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Professional JavaScript web developer... who simply can't wait for JSP to die the horrible death it deserves and thinks it would be a fine idea if Microsoft bought Canonical.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
logourl: /images/logo.png # Site logo
author: "Steve Hartzog"
author_thumbnail: "/images/avatar.jpg" # Author avatar
# Theme customization - please change from the defaults!
theme:
  # Color for links, etc
  highlight_color: "yellow" #205081" #205081" # "#272935"
  # Color for sidebar bar
  highlight_color: "black"
  # Social media links, leave blank to ignore
  social: 
    github: SteveHartzog
    twitter: shartzog
    # facebook: 
    gplus: +SteveHartzog
    # dribble: 
    # pinterest: 

  # Enable share buttons on post footer
  show_share_buttons: true

  # Show author picure, name and social links on post footer
  show_author_info: true

  # Disqus comments manager - shortname
  # disqus_shortname: zog-webcreate

  # Google Analytics/Webmaster key, leave blank to ignore
  google_analytics_key: UA-72529257-1
  google_webmaster_key: 

# Build settings
markdown: kramdown
#source: src
destination: _site

# Permalinks
permalink:        pretty

# Pagination config
paginate: 5

# Files/Folders to be excluded from generated _site folder
exclude: 
  - CNAME
  - Gemfile
  - Rakefile
  - README.md
  - .gitignore
  - .sass-cache
  - Gemfile.lock

# Sass conversion configs
sass:
  sass_dir: styles/
  style: :compressed
